language: ruby
cache: bundler

script: bundle exec rake site:deploy

notifications:
  email:
    recipients:
      - david@dmarby.se
    on_success: change
    on_failure: always
env:
  global:
    - secure: "gXudmhUT0J7/Ssld9T+soehqiX8gZNKVd+7A7/FCGhqZo9SCCvVq623TsxHdz39x7tnEwjeomDEdYH/jKBnSoNmUMvsxF6rBQy4CRtsNyNCEDvT51fZnxdY5N56K+BXP8xJZO1rS/23a21CQpf6snFlw30deRY7UCyoOzywfwWY="
    - secure: "EDefTCL/EaocZP8QHEPaC8+LPgf+uszTKgI76PoPGQ0F+PHt2DxV6S0ttoei/iOqolQWET1jWjAdT6g7IwBLeGAX+W3wG/ulj/4yeEImIFUqnYJR8QlFrJ8DuvRD9RfaTtt9hByOpVO7/XlgRjhaW0y2/VgJ7lHdfw6VtTrEcdU="
# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
