title:            Twitch Tips
description:      Describe your website.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://twitchtips.com
disqus_shortname: twitchtips

username: TwitchTips
repo: twitchtips
branch: master

lunr_search:
  excludes: [sitemap.xml,feed.xml]

# Owner/author information
owner:
  name:           Twitch Tips
  avatar:         bio-photo.png
  bio:            "An unofficial source for tips, tricks and tutorials for the game streaming platform, Twitch."
  email:          contact@twitchtips.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        TwitchTips
  facebook:       
  github:         TwitchTips         
  stackoverflow: 
  linkedin:       
  instagram:      
  lastfm:         
  tumblr: 
  pinterest: 
  foursquare: 
  steam: 
  dribbble: 
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-50140476-1
google_verify: oV6-uAnZIYjhC89f3QmTc1H38EiCF-vj7TiyV9UsWZs     
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: Get Started
    url: /get-started/
  - title: About
    url: /about/
  - title: Posts
    url: /posts/
  - title: Contribute
    url: /contribute/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]